services:
  suwayomi-notifier:
    build: .
    container_name: suwayomi-notifier
    environment:
      SUWAYOMI_HTTP: "http://suwayomi:4567"
      SUWAYOMI_WS: "ws://suwayomi:4567/api/graphql"
      SUWAYOMI_USERNAME: ""
      SUWAYOMI_PASSWORD: ""
      TELEGRAM_TOKEN: ""
      TELEGRAM_CHAT_ID: ""
      STATE_FILE: "/app/state/state.json"
    volumes:
      - ./state:/app/state
    restart: unless-stopped